filter:
    excluded_paths:
        - ".github/"
        - "tests/"
        - "vendor/"
        - "config/"

checks:
    php: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true

build:
    nodes:
        tests:
            dependencies:
                before:
                    - sudo apt-get update && sudo apt-get install -fyqq git ssh
    tests:
        override:
            - command: 'php ./vendor/bin/phpunit --coverage-clover=coverage-clover'
              coverage:
                  file: 'coverage-clover'
                  format: 'php-clover'
